In [ ]:
#important import libraries
import matplotlib.pyplot as plt
import tensorflow as tf
import numpy as np
import os
import cv2 as cv
from google.colab.patches import cv2_imshow
from IPython.display import clear_output
from google.colab import files

In [ ]:
#unzip the folder containing your images
!unzip "/content/Total Images.zip" -d "/content/"
!unzip "/content/Total GT.zip" -d "/content/"
clear_output()

In [ ]:
filenames_img=os.listdir('/content/Total Images')
filenames_GT=os.listdir('/content/Total GT')
filenames_imgsplit=[filename.replace('.tif', '') for filename in filenames_img]
filenames_GTsplit=[filename.replace('.txt', '') for filename in filenames_GT]

In [ ]:
def rotate_bound(image, angle):
    # grab the dimensions of the image and then determine the
    # center
    (h, w) = image.shape[:2]
    (cX, cY) = (w // 2, h // 2)
    # grab the rotation matrix (applying the negative of the
    # angle to rotate clockwise), then grab the sine and cosine
    # (i.e., the rotation components of the matrix)
    M = cv.getRotationMatrix2D((cX, cY), -angle, 1.0)
    cos = np.abs(M[0, 0])
    sin = np.abs(M[0, 1])
    # compute the new bounding dimensions of the image
    nW = int((h * sin) + (w * cos))
    nH = int((h * cos) + (w * sin))
    # adjust the rotation matrix to take into account translation
    M[0, 2] += (nW / 2) - cX
    M[1, 2] += (nH / 2) - cY
    # perform the actual rotation and return the image
    return cv.warpAffine(image, M, (nW, nH))

In [ ]:
!mkdir labels_aug
!mkdir img_aug
for m in range(len(filenames_img)-1):
  img=cv.imread('/content/Total Images/'+filenames_img[m],0)
  label_file = open('/content/Total GT/'+filenames_GT[m], "r") 
  label=label_file.read()
  with open("/content/labels_aug/"+filenames_GTsplit[m]+'_rot.txt', 'w') as fid: # 'w' creates a new file
          fid.write(label)
  print(img)
  img=rotate_bound(img,3)
  cv.imwrite("/content/img_aug/"+filenames_imgsplit[m]+"_rot.tif", img)

Streaming output truncated to the last 5000 lines.
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 .

In [ ]:
!zip -r /content/img_aug.zip  /content/img_aug
files.download("/content/img_aug.zip") 
!zip -r /content/labels_aug.zip /content/labels_aug
files.download("/content/labels_aug.zip")

Streaming output truncated to the last 5000 lines.
  adding: content/img_aug/AHTD3A1066_Para4_5_word14_rot.tif (deflated 5%)
  adding: content/img_aug/AHTD3A1012_Para4_3_word1_rot.tif (deflated 7%)
  adding: content/img_aug/AHTD3A0164_Para4_2_word8_rot.tif (deflated 9%)
  adding: content/img_aug/AHTD3A0080_Para4_1_word20_rot.tif (deflated 9%)
  adding: content/img_aug/AHTD3A0586_Para4_0_word24_rot.tif (deflated 6%)
  adding: content/img_aug/AHTD3A0149_Para4_2_word28_rot.tif (deflated 4%)
  adding: content/img_aug/AHTD3A0139_Para1_7_word1_rot.tif (deflated 8%)
  adding: content/img_aug/AHTD3A0335_Para4_2_word14_rot.tif (deflated 3%)
  adding: content/img_aug/AHTD3A0586_Para4_3_word23_rot.tif (deflated 6%)
  adding: content/img_aug/AHTD3A0006_Para1_3_word8_rot.tif (deflated 4%)
  adding: content/img_aug/AHTD3A0276_Para1_1_word12_rot.tif (deflated 6%)
  adding: content/img_aug/AHTD3A0137_Para1_4_word7_rot.tif (deflated 5%)
  adding: content/img_aug/AHTD3A0137_Para1_1_word9_rot.tif (deflat

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>

Streaming output truncated to the last 5000 lines.
  adding: content/labels_aug/AHTD3A0004_Para1_6_word14_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0139_Para4_5_word2_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0757_Para1_2_word10_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0016_Para1_4_word7_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0586_Para4_4_word1_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0195_Para1_2_word12_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0300_Para1_2_word10_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0003_Para1_2_word15_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0855_Para4_1_word18_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0587_Para4_5_word2_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0313_Para4_3_word6_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A1066_Para4_5_word20_rot.txt (stored 0%)
  adding: content/labels_aug/AHTD3A0080_Para4_1_word11

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>