In [1]:
import tensorflow as tf
print("TensorFlow version:", tf.__version__)

TensorFlow version: 2.15.0


In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

11490434/11490434 [==============================] - 0s 0us/step


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.71437764, -0.21459974, -0.24951729,  0.3269424 , -0.12906727,
        -0.00949717,  0.2714343 ,  0.05786566,  0.04086888, -0.6772021 ]],
      dtype=float32)

In [5]:
tf.nn.softmax(predictions).numpy()

array([[0.18904833, 0.07466604, 0.07210387, 0.12832518, 0.08133349,
        0.09166384, 0.12139618, 0.09805129, 0.09639882, 0.04701294]],
      dtype=float32)

In [6]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [7]:
loss_fn(y_train[:1], predictions).numpy()

2.3896275

In [8]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [9]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.2914 - accuracy: 0.9139
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.1411 - accuracy: 0.9577
Epoch 3/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.1062 - accuracy: 0.9680
Epoch 4/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0868 - accuracy: 0.9726
Epoch 5/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0741 - accuracy: 0.9771


In [10]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - loss: 0.0735 - accuracy: 0.9769 - 688ms/epoch - 2ms/step


[0.07353226840496063, 0.9768999814987183]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.20525109e-08, 3.49380436e-08, 1.56460624e-06, 1.08104381e-04,
        1.06915189e-11, 8.21387545e-08, 1.14133480e-14, 9.99881387e-01,
        5.21813988e-08, 8.82004679e-06],
       [4.24124202e-08, 3.49176189e-05, 9.99961615e-01, 3.23772838e-06,
        5.06789935e-19, 2.73405636e-08, 1.59006452e-09, 1.78204822e-13,
        2.24934780e-07, 1.37848974e-13],
       [1.87683771e-08, 9.99804914e-01, 1.60548771e-05, 1.70790111e-06,
        2.05928627e-05, 3.09618429e-07, 5.24692723e-06, 1.18614094e-04,
        3.21493571e-05, 3.21620831e-07],
       [9.99836564e-01, 5.55680257e-09, 1.20337845e-05, 2.95792051e-06,
        5.59237945e-09, 3.27795283e-06, 1.06378764e-04, 2.76437404e-05,
        5.85357498e-07, 1.05984791e-05],
       [2.18611603e-06, 1.11154774e-09, 1.00971533e-06, 4.86555578e-08,
        9.99526381e-01, 2.77071361e-08, 1.46486364e-05, 1.84098644e-05,
        9.60298621e-07, 4.36390721e-04]], dtype=float32)>